// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/plugin/v1/plugin.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginService_Register_FullMethodName  = "/plugin.v1.PluginService/Register"
	PluginService_Heartbeat_FullMethodName = "/plugin.v1.PluginService/Heartbeat"
)

// PluginServiceClient is the client API for PluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginService is implemented by the BACKEND. Plugins call it to register.
type PluginServiceClient interface {
	// Register is called by a plugin on startup to announce itself.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Heartbeat keeps the plugin connection alive.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type pluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginServiceClient(cc grpc.ClientConnInterface) PluginServiceClient {
	return &pluginServiceClient{cc}
}

func (c *pluginServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, PluginService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, PluginService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServiceServer is the server API for PluginService service.
// All implementations must embed UnimplementedPluginServiceServer
// for forward compatibility.
//
// PluginService is implemented by the BACKEND. Plugins call it to register.
type PluginServiceServer interface {
	// Register is called by a plugin on startup to announce itself.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Heartbeat keeps the plugin connection alive.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedPluginServiceServer()
}

// UnimplementedPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServiceServer struct{}

func (UnimplementedPluginServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedPluginServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedPluginServiceServer) mustEmbedUnimplementedPluginServiceServer() {}
func (UnimplementedPluginServiceServer) testEmbeddedByValue()                       {}

// UnsafePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServiceServer will
// result in compilation errors.
type UnsafePluginServiceServer interface {
	mustEmbedUnimplementedPluginServiceServer()
}

func RegisterPluginServiceServer(s grpc.ServiceRegistrar, srv PluginServiceServer) {
	// If the following call panics, it indicates UnimplementedPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginService_ServiceDesc, srv)
}

func _PluginService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginService_ServiceDesc is the grpc.ServiceDesc for PluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.v1.PluginService",
	HandlerType: (*PluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _PluginService_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _PluginService_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/plugin/v1/plugin.proto",
}

const (
	TaskExecutorService_GetTaskDefinitions_FullMethodName = "/plugin.v1.TaskExecutorService/GetTaskDefinitions"
	TaskExecutorService_ValidateInput_FullMethodName      = "/plugin.v1.TaskExecutorService/ValidateInput"
	TaskExecutorService_ExecuteSync_FullMethodName        = "/plugin.v1.TaskExecutorService/ExecuteSync"
	TaskExecutorService_ExecuteAsync_FullMethodName       = "/plugin.v1.TaskExecutorService/ExecuteAsync"
)

// TaskExecutorServiceClient is the client API for TaskExecutorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TaskExecutorService is implemented by PLUGINS. The backend calls it to run tasks.
type TaskExecutorServiceClient interface {
	// GetTaskDefinitions returns all tasks this plugin can execute.
	GetTaskDefinitions(ctx context.Context, in *GetTaskDefinitionsRequest, opts ...grpc.CallOption) (*GetTaskDefinitionsResponse, error)
	// ValidateInput validates user input before execution.
	ValidateInput(ctx context.Context, in *ValidateInputRequest, opts ...grpc.CallOption) (*ValidateInputResponse, error)
	// ExecuteSync executes a short-lived task synchronously.
	ExecuteSync(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	// ExecuteAsync executes a long-running task and streams progress.
	ExecuteAsync(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskProgress], error)
}

type taskExecutorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskExecutorServiceClient(cc grpc.ClientConnInterface) TaskExecutorServiceClient {
	return &taskExecutorServiceClient{cc}
}

func (c *taskExecutorServiceClient) GetTaskDefinitions(ctx context.Context, in *GetTaskDefinitionsRequest, opts ...grpc.CallOption) (*GetTaskDefinitionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskDefinitionsResponse)
	err := c.cc.Invoke(ctx, TaskExecutorService_GetTaskDefinitions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskExecutorServiceClient) ValidateInput(ctx context.Context, in *ValidateInputRequest, opts ...grpc.CallOption) (*ValidateInputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateInputResponse)
	err := c.cc.Invoke(ctx, TaskExecutorService_ValidateInput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskExecutorServiceClient) ExecuteSync(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, TaskExecutorService_ExecuteSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskExecutorServiceClient) ExecuteAsync(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskExecutorService_ServiceDesc.Streams[0], TaskExecutorService_ExecuteAsync_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TaskRequest, TaskProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskExecutorService_ExecuteAsyncClient = grpc.ServerStreamingClient[TaskProgress]

// TaskExecutorServiceServer is the server API for TaskExecutorService service.
// All implementations must embed UnimplementedTaskExecutorServiceServer
// for forward compatibility.
//
// TaskExecutorService is implemented by PLUGINS. The backend calls it to run tasks.
type TaskExecutorServiceServer interface {
	// GetTaskDefinitions returns all tasks this plugin can execute.
	GetTaskDefinitions(context.Context, *GetTaskDefinitionsRequest) (*GetTaskDefinitionsResponse, error)
	// ValidateInput validates user input before execution.
	ValidateInput(context.Context, *ValidateInputRequest) (*ValidateInputResponse, error)
	// ExecuteSync executes a short-lived task synchronously.
	ExecuteSync(context.Context, *TaskRequest) (*TaskResponse, error)
	// ExecuteAsync executes a long-running task and streams progress.
	ExecuteAsync(*TaskRequest, grpc.ServerStreamingServer[TaskProgress]) error
	mustEmbedUnimplementedTaskExecutorServiceServer()
}

// UnimplementedTaskExecutorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskExecutorServiceServer struct{}

func (UnimplementedTaskExecutorServiceServer) GetTaskDefinitions(context.Context, *GetTaskDefinitionsRequest) (*GetTaskDefinitionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskDefinitions not implemented")
}
func (UnimplementedTaskExecutorServiceServer) ValidateInput(context.Context, *ValidateInputRequest) (*ValidateInputResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateInput not implemented")
}
func (UnimplementedTaskExecutorServiceServer) ExecuteSync(context.Context, *TaskRequest) (*TaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteSync not implemented")
}
func (UnimplementedTaskExecutorServiceServer) ExecuteAsync(*TaskRequest, grpc.ServerStreamingServer[TaskProgress]) error {
	return status.Error(codes.Unimplemented, "method ExecuteAsync not implemented")
}
func (UnimplementedTaskExecutorServiceServer) mustEmbedUnimplementedTaskExecutorServiceServer() {}
func (UnimplementedTaskExecutorServiceServer) testEmbeddedByValue()                             {}

// UnsafeTaskExecutorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskExecutorServiceServer will
// result in compilation errors.
type UnsafeTaskExecutorServiceServer interface {
	mustEmbedUnimplementedTaskExecutorServiceServer()
}

func RegisterTaskExecutorServiceServer(s grpc.ServiceRegistrar, srv TaskExecutorServiceServer) {
	// If the following call panics, it indicates UnimplementedTaskExecutorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskExecutorService_ServiceDesc, srv)
}

func _TaskExecutorService_GetTaskDefinitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskDefinitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskExecutorServiceServer).GetTaskDefinitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskExecutorService_GetTaskDefinitions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskExecutorServiceServer).GetTaskDefinitions(ctx, req.(*GetTaskDefinitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskExecutorService_ValidateInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskExecutorServiceServer).ValidateInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskExecutorService_ValidateInput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskExecutorServiceServer).ValidateInput(ctx, req.(*ValidateInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskExecutorService_ExecuteSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskExecutorServiceServer).ExecuteSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskExecutorService_ExecuteSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskExecutorServiceServer).ExecuteSync(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskExecutorService_ExecuteAsync_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TaskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaskExecutorServiceServer).ExecuteAsync(m, &grpc.GenericServerStream[TaskRequest, TaskProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskExecutorService_ExecuteAsyncServer = grpc.ServerStreamingServer[TaskProgress]

// TaskExecutorService_ServiceDesc is the grpc.ServiceDesc for TaskExecutorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskExecutorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "plugin.v1.TaskExecutorService",
	HandlerType: (*TaskExecutorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTaskDefinitions",
			Handler:    _TaskExecutorService_GetTaskDefinitions_Handler,
		},
		{
			MethodName: "ValidateInput",
			Handler:    _TaskExecutorService_ValidateInput_Handler,
		},
		{
			MethodName: "ExecuteSync",
			Handler:    _TaskExecutorService_ExecuteSync_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteAsync",
			Handler:       _TaskExecutorService_ExecuteAsync_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/plugin/v1/plugin.proto",
}
