// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/plugin/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	GrpcAddress   string                 `protobuf:"bytes,3,opt,name=grpc_address,json=grpcAddress,proto3" json:"grpc_address,omitempty"` // Address where the plugin's TaskExecutorService listens
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RegisterRequest) GetGrpcAddress() string {
	if x != nil {
		return x.GrpcAddress
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetTaskDefinitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskDefinitionsRequest) Reset() {
	*x = GetTaskDefinitionsRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskDefinitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskDefinitionsRequest) ProtoMessage() {}

func (x *GetTaskDefinitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskDefinitionsRequest.ProtoReflect.Descriptor instead.
func (*GetTaskDefinitionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

type GetTaskDefinitionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*TaskDefinition      `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskDefinitionsResponse) Reset() {
	*x = GetTaskDefinitionsResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskDefinitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskDefinitionsResponse) ProtoMessage() {}

func (x *GetTaskDefinitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskDefinitionsResponse.ProtoReflect.Descriptor instead.
func (*GetTaskDefinitionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskDefinitionsResponse) GetTasks() []*TaskDefinition {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type TaskDefinition struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slug                string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category            string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	IsSync              bool                   `protobuf:"varint,5,opt,name=is_sync,json=isSync,proto3" json:"is_sync,omitempty"`
	InputSchema         string                 `protobuf:"bytes,6,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"` // JSON Schema string
	RequiredPermissions []string               `protobuf:"bytes,7,rep,name=required_permissions,json=requiredPermissions,proto3" json:"required_permissions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TaskDefinition) Reset() {
	*x = TaskDefinition{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDefinition) ProtoMessage() {}

func (x *TaskDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDefinition.ProtoReflect.Descriptor instead.
func (*TaskDefinition) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *TaskDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskDefinition) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *TaskDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskDefinition) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *TaskDefinition) GetIsSync() bool {
	if x != nil {
		return x.IsSync
	}
	return false
}

func (x *TaskDefinition) GetInputSchema() string {
	if x != nil {
		return x.InputSchema
	}
	return ""
}

func (x *TaskDefinition) GetRequiredPermissions() []string {
	if x != nil {
		return x.RequiredPermissions
	}
	return nil
}

type ValidateInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskSlug      string                 `protobuf:"bytes,1,opt,name=task_slug,json=taskSlug,proto3" json:"task_slug,omitempty"`
	InputJson     string                 `protobuf:"bytes,2,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateInputRequest) Reset() {
	*x = ValidateInputRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateInputRequest) ProtoMessage() {}

func (x *ValidateInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateInputRequest.ProtoReflect.Descriptor instead.
func (*ValidateInputRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateInputRequest) GetTaskSlug() string {
	if x != nil {
		return x.TaskSlug
	}
	return ""
}

func (x *ValidateInputRequest) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

type ValidateInputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateInputResponse) Reset() {
	*x = ValidateInputResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateInputResponse) ProtoMessage() {}

func (x *ValidateInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateInputResponse.ProtoReflect.Descriptor instead.
func (*ValidateInputResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateInputResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateInputResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type UserContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserContext) Reset() {
	*x = UserContext{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserContext) ProtoMessage() {}

func (x *UserContext) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserContext.ProtoReflect.Descriptor instead.
func (*UserContext) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *UserContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserContext) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserContext) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserContext) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	TaskSlug      string                 `protobuf:"bytes,2,opt,name=task_slug,json=taskSlug,proto3" json:"task_slug,omitempty"`
	InputJson     string                 `protobuf:"bytes,3,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	User          *UserContext           `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *TaskRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *TaskRequest) GetTaskSlug() string {
	if x != nil {
		return x.TaskSlug
	}
	return ""
}

func (x *TaskRequest) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

func (x *TaskRequest) GetUser() *UserContext {
	if x != nil {
		return x.User
	}
	return nil
}

type TaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputJson    string                 `protobuf:"bytes,1,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResponse) Reset() {
	*x = TaskResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResponse) ProtoMessage() {}

func (x *TaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResponse.ProtoReflect.Descriptor instead.
func (*TaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *TaskResponse) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *TaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TaskProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgressPct   int32                  `protobuf:"varint,1,opt,name=progress_pct,json=progressPct,proto3" json:"progress_pct,omitempty"` // 0-100
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                           // running, completed, failed
	OutputJson    string                 `protobuf:"bytes,4,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"` // set when status=completed
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`                             // set when status=failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskProgress) Reset() {
	*x = TaskProgress{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskProgress) ProtoMessage() {}

func (x *TaskProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskProgress.ProtoReflect.Descriptor instead.
func (*TaskProgress) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *TaskProgress) GetProgressPct() int32 {
	if x != nil {
		return x.ProgressPct
	}
	return 0
}

func (x *TaskProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TaskProgress) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskProgress) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *TaskProgress) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_proto_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/plugin/v1/plugin.proto\x12\tplugin.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x84\x01\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\fgrpc_address\x18\x03 \x01(\tR\vgrpcAddress\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"e\n" +
	"\x10RegisterResponse\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"/\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\"#\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x1b\n" +
	"\x19GetTaskDefinitionsRequest\"M\n" +
	"\x1aGetTaskDefinitionsResponse\x12/\n" +
	"\x05tasks\x18\x01 \x03(\v2\x19.plugin.v1.TaskDefinitionR\x05tasks\"\xe5\x01\n" +
	"\x0eTaskDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x17\n" +
	"\ais_sync\x18\x05 \x01(\bR\x06isSync\x12!\n" +
	"\finput_schema\x18\x06 \x01(\tR\vinputSchema\x121\n" +
	"\x14required_permissions\x18\a \x03(\tR\x13requiredPermissions\"R\n" +
	"\x14ValidateInputRequest\x12\x1b\n" +
	"\ttask_slug\x18\x01 \x01(\tR\btaskSlug\x12\x1d\n" +
	"\n" +
	"input_json\x18\x02 \x01(\tR\tinputJson\"E\n" +
	"\x15ValidateInputResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\"n\n" +
	"\vUserContext\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\"\x98\x01\n" +
	"\vTaskRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1b\n" +
	"\ttask_slug\x18\x02 \x01(\tR\btaskSlug\x12\x1d\n" +
	"\n" +
	"input_json\x18\x03 \x01(\tR\tinputJson\x12*\n" +
	"\x04user\x18\x04 \x01(\v2\x16.plugin.v1.UserContextR\x04user\"_\n" +
	"\fTaskResponse\x12\x1f\n" +
	"\voutput_json\x18\x01 \x01(\tR\n" +
	"outputJson\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x9a\x01\n" +
	"\fTaskProgress\x12!\n" +
	"\fprogress_pct\x18\x01 \x01(\x05R\vprogressPct\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\voutput_json\x18\x04 \x01(\tR\n" +
	"outputJson\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error2\x9c\x01\n" +
	"\rPluginService\x12C\n" +
	"\bRegister\x12\x1a.plugin.v1.RegisterRequest\x1a\x1b.plugin.v1.RegisterResponse\x12F\n" +
	"\tHeartbeat\x12\x1b.plugin.v1.HeartbeatRequest\x1a\x1c.plugin.v1.HeartbeatResponse2\xcf\x02\n" +
	"\x13TaskExecutorService\x12a\n" +
	"\x12GetTaskDefinitions\x12$.plugin.v1.GetTaskDefinitionsRequest\x1a%.plugin.v1.GetTaskDefinitionsResponse\x12R\n" +
	"\rValidateInput\x12\x1f.plugin.v1.ValidateInputRequest\x1a .plugin.v1.ValidateInputResponse\x12>\n" +
	"\vExecuteSync\x12\x16.plugin.v1.TaskRequest\x1a\x17.plugin.v1.TaskResponse\x12A\n" +
	"\fExecuteAsync\x12\x16.plugin.v1.TaskRequest\x1a\x17.plugin.v1.TaskProgress0\x01B=Z;github.com/justlab/justservice/api/proto/plugin/v1;pluginv1b\x06proto3"

var (
	file_proto_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_proto_plugin_v1_plugin_proto_rawDescData []byte
)

func file_proto_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_proto_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_proto_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugin_v1_plugin_proto_rawDesc), len(file_proto_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_proto_plugin_v1_plugin_proto_rawDescData
}

var file_proto_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_plugin_v1_plugin_proto_goTypes = []any{
	(*RegisterRequest)(nil),            // 0: plugin.v1.RegisterRequest
	(*RegisterResponse)(nil),           // 1: plugin.v1.RegisterResponse
	(*HeartbeatRequest)(nil),           // 2: plugin.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),          // 3: plugin.v1.HeartbeatResponse
	(*GetTaskDefinitionsRequest)(nil),  // 4: plugin.v1.GetTaskDefinitionsRequest
	(*GetTaskDefinitionsResponse)(nil), // 5: plugin.v1.GetTaskDefinitionsResponse
	(*TaskDefinition)(nil),             // 6: plugin.v1.TaskDefinition
	(*ValidateInputRequest)(nil),       // 7: plugin.v1.ValidateInputRequest
	(*ValidateInputResponse)(nil),      // 8: plugin.v1.ValidateInputResponse
	(*UserContext)(nil),                // 9: plugin.v1.UserContext
	(*TaskRequest)(nil),                // 10: plugin.v1.TaskRequest
	(*TaskResponse)(nil),               // 11: plugin.v1.TaskResponse
	(*TaskProgress)(nil),               // 12: plugin.v1.TaskProgress
}
var file_proto_plugin_v1_plugin_proto_depIdxs = []int32{
	6,  // 0: plugin.v1.GetTaskDefinitionsResponse.tasks:type_name -> plugin.v1.TaskDefinition
	9,  // 1: plugin.v1.TaskRequest.user:type_name -> plugin.v1.UserContext
	0,  // 2: plugin.v1.PluginService.Register:input_type -> plugin.v1.RegisterRequest
	2,  // 3: plugin.v1.PluginService.Heartbeat:input_type -> plugin.v1.HeartbeatRequest
	4,  // 4: plugin.v1.TaskExecutorService.GetTaskDefinitions:input_type -> plugin.v1.GetTaskDefinitionsRequest
	7,  // 5: plugin.v1.TaskExecutorService.ValidateInput:input_type -> plugin.v1.ValidateInputRequest
	10, // 6: plugin.v1.TaskExecutorService.ExecuteSync:input_type -> plugin.v1.TaskRequest
	10, // 7: plugin.v1.TaskExecutorService.ExecuteAsync:input_type -> plugin.v1.TaskRequest
	1,  // 8: plugin.v1.PluginService.Register:output_type -> plugin.v1.RegisterResponse
	3,  // 9: plugin.v1.PluginService.Heartbeat:output_type -> plugin.v1.HeartbeatResponse
	5,  // 10: plugin.v1.TaskExecutorService.GetTaskDefinitions:output_type -> plugin.v1.GetTaskDefinitionsResponse
	8,  // 11: plugin.v1.TaskExecutorService.ValidateInput:output_type -> plugin.v1.ValidateInputResponse
	11, // 12: plugin.v1.TaskExecutorService.ExecuteSync:output_type -> plugin.v1.TaskResponse
	12, // 13: plugin.v1.TaskExecutorService.ExecuteAsync:output_type -> plugin.v1.TaskProgress
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_plugin_v1_plugin_proto_init() }
func file_proto_plugin_v1_plugin_proto_init() {
	if File_proto_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugin_v1_plugin_proto_rawDesc), len(file_proto_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_proto_plugin_v1_plugin_proto_depIdxs,
		MessageInfos:      file_proto_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_proto_plugin_v1_plugin_proto = out.File
	file_proto_plugin_v1_plugin_proto_goTypes = nil
	file_proto_plugin_v1_plugin_proto_depIdxs = nil
}
