apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "justservice.fullname" . }}-config
  labels:
    {{- include "justservice.labels" . | nindent 4 }}
data:
  log-level: {{ .Values.config.logLevel | quote }}
  log-format: {{ .Values.config.logFormat | quote }}
  oidc-public-base-url: {{ .Values.config.oidc.publicBaseUrl | quote }}
