apiVersion: v1
kind: Secret
metadata:
  name: {{ include "justservice.fullname" . }}-secret
  labels:
    {{- include "justservice.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ required "config.jwtSecret is required" .Values.config.jwtSecret | quote }}
  database-dsn: {{ include "justservice.databaseDsn" . | quote }}
